### ISSUE TITLE
5.0.1 is not working - Property does not exist on type 'Browser'

### ISSUE THREAD

**Issue by user7699** [wswebcreation/wdio-image-comparison-service#104]
> **NOTE: Be aware of the fact that this module is only a plugin that provides all functionality from [`webdriver-image-comparison`](https://github.com/wswebcreation/webdriver-image-comparison). So please check if this is an issue with this plugin or with `webdriver-image-comparison`.**

**Environment (please complete the following information):**
```
        "@wdio/cli": "^7.23.0",
        "@wdio/local-runner": "^7.23.0",
        "@wdio/mocha-framework": "^7.23.0",
        "@wdio/spec-reporter": "^7.23.0",
        "chromedriver": "^104.0.0",
        "ts-node": "^10.9.1",
        "typescript": "^4.8.2",
        "wdio-chromedriver-service": "^7.3.2",
        "wdio-image-comparison-service": "^5.0.1",
        "webpack-merge": "^5.8.0",
        "puppeteer": "^15.4.2"
```
ts-config: 
```.json
{
    "compilerOptions": {
        "types": ["node", "webdriverio/async", "@wdio/mocha-framework", "expect-webdriverio", "wdio-image-comparison-service"],
        "strictPropertyInitialization": true,
        "strictNullChecks": true,
        "target": "ES5"
    },
    "include": ["./src/**/*.ts"]
}
```

**Config of WebdriverIO + wdio-image-comparison-service**
No configuration - use the default methods provided by the docs. 

**Describe the bug**

Try using any of the methods that comes with the service - https://webdriver.io/docs/wdio-image-comparison-service#writing-tests

I get the same error, no matter which one I use

![bild](https://user-images.githubusercontent.com/93139584/199918210-ec2364da-81d7-493d-90a2-e8a52fc3919b.png)

If I go back to 5.0.0, everything is working fine. 

**To Reproduce**

Use any of the methods listed here: https://webdriver.io/docs/wdio-image-comparison-service#writing-tests and you should get the same error. 

**Expected behavior**
Property should exist on browser. 

**Additional context**
Thank you for this amazing tool :)

**Comment by wswebcreation** [comment]
Sorry, not sure what happened. I'll check with the original committer to see what issue he had. It's my bad that I didn't check this properly, sorry for the inconvenience. 
I've released https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v5.0.2. Can you try it again?

**Comment by pip8786** [comment]
@wswebcreation this is the same issue. That's why I was saying we should use Browser<Mode> but you told me to use Browser<"async"> specifically. Doing Browser<Mode> would allow both to work (async and sync).

**Comment by pip8786** [comment]
@wswebcreation Did you see my reply (here and on Gitter)?
