### ISSUE TITLE
On some websites saveFullPageScreen() is not scrolling to the bottom of the page

### ISSUE THREAD

**Issue by emanuelprisecaru** [wswebcreation/wdio-image-comparison-service#107]
**Environment (please complete the following information):**
 - Node.js version: v17.0.1
 - Browser name and version: Chrome 108/latest
 - Platform name and version: MacOs Monterey
 - WebdriverIO version: 7.27.0
 - wdio-image-comparison-service version: 5.0.2

**Config of WebdriverIO + wdio-image-comparison-service**
services: [
    [
      "image-comparison",
      {
        // Some options, see the docs for more
        baselineFolder: join(process.cwd(), "./tests/sauceLabsBaseline/"),
        formatImageName: "{tag}-{logName}-{width}x{height}",
        screenshotPath: join(process.cwd(), ".tmp/"),
        savePerInstance: true,
        autoSaveBaseline: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        ignoreNothing: true,
        // NOTE: When you are testing a hybrid app please use this setting
        // isHybridApp: true,
        // Options for the tabbing image
        tabbableOptions: {
          circle: {
            size: 18,
            fontSize: 18,
            // ...
          },
          line: {
            color: "#ff221a", // hex-code or for example words like `red|black|green`
            width: 3,
          },
        },
        // ... more options
      },
    ]
]

**Describe the bug**
On some websites with image that takes the entire visible part of the viewport, the checkFullPageScreen() does not seem to be scrolling. it takes several screenshots of the same top viewport instead of scrolling and taking screenshot.

**To Reproduce**
Access https://smol-development.com/
attempt to take full page screenshot
await browser.saveFullPageScreen("fullPage", {
      fullPageScrollTimeout: 3000,
    });

**Expected behavior**
A screenshot of the entire page should be taken.

**Actual behavior**
Several screenshots of the same top viewport are taken
![fullPage--1200x1011](https://user-images.githubusercontent.com/37046282/207635673-c41b68a6-32c4-4e76-811c-6276ae701c42.png)

**Comment by wswebcreation** [comment]
Tested this

```js
describe('issue-107', () => {
    it('should be able to create a full page screenshot', async () => {
        await driver.url('https://smol-development.com/')
        await browser.saveFullPageScreen('smol-development', {
            fullPageScrollTimeout: 3000,
        })
    })
})
```

and the output was this

![smol-development-chrome-latest-1366x768](https://user-images.githubusercontent.com/11979740/234484001-77849ff2-c3c8-4098-8e6b-39e94bc3b824.png)

When I change it to this

```js
describe('issue-107', () => {
    it('should be able to create a full page screenshot', async () => {
        await driver.url('https://smol-development.com/')
        await $('#close-cookie-consent').click()
        await browser.saveFullPageScreen('smol-development', {
            // Hide the header after the first scroll
            hideAfterFirstScroll: [await $('.site-header-box')],
            fullPageScrollTimeout: 3000,
        })
    })
})
```

the output it this

![smol-development-chrome-latest-1366x768](https://user-images.githubusercontent.com/11979740/234484776-b8366d8a-c8d1-4c41-b625-7cb7d5cd75b8.png)

So closing this ticket as:
- it seemed to be solved
- it was always working
