### ISSUE TITLE
Unable to install wdio-image-comparison-service

### ISSUE THREAD

**Issue by Searcher865** [wswebcreation/wdio-image-comparison-service#112]
**Environment (please complete the following information):**
 - Node.js version: [v18.14.0]
 - NPM version: [9.3.1]
 - Browser name and version: [Chrome 109.0.5414.119]
 - Platform name and version: [macOS Ventura 13.2 (22D49) - macbook air m1]
 - Framework name and version: [webdriverIO 8]
 - Plugin name and version: [last]
 - webdriver-image-comparison version: [last]

**Describe the bug**
Unable to install wdio-image-comparison

**To Reproduce**
1) try npm i wdio-image-comparison 
or
wdio-image-comparison-service
or 
npm init wdio .   (select during initialization wdio-image-comparison-service)
[Include code or an example repository that can easily be set up]

**Expected behavior**
Successful installation

**Log**

[logs](https://drive.google.com/file/d/1FwtsO561z8itYXSRvuzcbwRJSs3ZtS85/view?usp=share_link)

**Comment by wswebcreation** [comment]
You're on NodeJS 18, there's an open ticket for the core of this module to upgrade it to that. It hasn't been fixed and released. If you revert back to NodeJS 16 it will work

**Comment by fbell123** [comment]
this is actually an issue with `canvas` as there isn't currently and arm64 build, there is a workaround for the time being https://github.com/Automattic/node-canvas/wiki/Installation:-Mac-OS-X

I used the homebrew installation and it works

For info, this is the issue on node-canvas board https://github.com/Automattic/node-canvas/issues/1662

**Comment by GRmeB** [comment]
I'm using Mac OS Ventura 13.2.1 with Node.js 18.12.1 and image comparison plugin 5.0.2. the workaround with homebrew is not working for me. is it maybe because of node.js version? I'm a little bit frustrated on that canvas issue.

**Comment by wswebcreation** [comment]
This should be fixed with https://github.com/wswebcreation/wdio-image-comparison-service/pull/118
