### ISSUE TITLE
Unable to install wdio-image-comparison-service

### ISSUE THREAD

**Issue by andwaee** [wswebcreation/wdio-image-comparison-service#120]
I am trying to install wdio-image-comparison-service  on a Mac Monterey 12.6.5 with node 16+ but I am getting the error below.

Error: 
npm ERR! code 1
npm ERR! path /Users/john.andrei.estrella/Desktop/DOF-GAS/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! SOLINK_MODULE(target) Release/canvas-postbuild.node
npm ERR!   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
npm ERR! Failed to execute

**Comment by wswebcreation** [comment]
CAn you please provide the needed info that was requested when you opened the ticket?
