### ISSUE TITLE
Full Page screenshot is only capturing the image of the viewport. Is any there specific setting options required?

### ISSUE THREAD

**Issue by sureshkandasamy** [wswebcreation/wdio-image-comparison-service#13]
Full Page screenshot is only capturing the image of the viewport. It shows a blank page for rest of the screen in the screenshot.
I am a newbie and I tried a simple test described in your example in Chrome. Scree
Is any there specific setting options required?

**Environment (please complete the following information):**
 - Node.js version: 8.9.4
 - NPM version: 5.6.0
 - Browser name and version: Chrome 75
 - Platform name and version: Windows 10
 - WebdriverIO version: 5.11.13
 - wdio-image-comparison-service version: 1.5.0
- mocha version: 6.2.0

**Additional context**

**Test.js**

```js
var chai = require('chai');
const chaiWebdriver = require('chai-webdriverio').default;
chai.use(chaiWebdriver(browser));
const expect = chai.expect;

describe('Example', () => {
    beforeEach(() => {
      browser.url('https://webdriver.io');    
    });   
    
    it('should compare successful with a baseline', () => {              
        // Check a full page screens
        expect(browser.checkFullPageScreen('fullPage', { 
            fullPageScrollTimeout: '3000',
         })).to.equal(0);
    });
  });
```

**wdio.config.js**
```js
services: ['selenium-standalone','chromedriver', 'firefox-profile',
    ['image-comparison', 
    // The options
    {
        // Some options, see the docs for more
        //baselineFolder: join(process.cwd(), './screenshots/auBaseline/'),
        actualFolder: join(process.cwd(), './screenshots/testActual'),
        baselineFolder: join(process.cwd(), './screenshots/testBaseline'),
        diffFolder: join(process.cwd(), './screenshots/testDiff'),
        formatImageName: '{tag}-{logName}-{width}x{height}',
        screenshotPath: join(process.cwd(), './screenshots/'),
        savePerInstance: true,
        autoSaveBaseline: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        // ... more options
    }]
],
```
![fullPage--1050x660](https://user-images.githubusercontent.com/11058865/62589974-48964880-b90e-11e9-8abd-40b118e09bf9.png)

**Comment by wswebcreation** [comment]
@sureshkandasamy 

Thanks for filling an issue, this one is related to this https://github.com/wswebcreation/webdriver-image-comparison/issues/31 and will be fixed there. I'll keep this open for tracking

**Comment by wswebcreation** [comment]
@sureshkandasamy 

I've released a new version, can you install that one and check if it is fixed, if so, please close the iissue

**Comment by wswebcreation** [comment]
Going to close it because it works as expected now

![fullPage-chrome-1200x1373-dpr-1](https://user-images.githubusercontent.com/11979740/63639489-dc4c7080-c693-11e9-8968-e70201f7c9f7.png)
