### ISSUE TITLE
checkFullPageScreen is not taking options into account when defining properties(baselineFolder, screenshotPath,etc) - Mobile

### ISSUE THREAD

**Issue by gmontoya190** [wswebcreation/wdio-image-comparison-service#14]
**Environment (please complete the following information):**
 - Node.js version: 8.16.0
 - NPM version: 6.4.1
 - Browser name and version: iPhone XS, 
 - Platform name and version: iOS 12.1
 - WebdriverIO version: 5.9.6
 - wdio-image-comparison-service version: 1.5.0
-  browserstack-service : 5.8.0

**Config of WebdriverIO + wdio-image-comparison-service**

**wdio-image-comparison-service configuration**
```
module.exports = {
  services: [

    ['image-comparison',
      {
        autoSaveBaseline: true,
      }],

  ],
```
**wdio-configuration**
```
const projectConfig = {
  baseUrl: 'http://bs-local.com:8080',
  debug: true,
  maxInstances: 5,
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    compilers: ['js:babel-core/register'],
    timeout: 10 * 60 * 1000,
  },
  specs: ['**/test/visual/**/*.js'],
  before() {
    global.expect = expect;
  },
  user: '',
  key: '',
  orientations: ['landscape', 'portrait'],
  automationName: 'UIAutomator2',
  commonCapabilities: {
    project: 'UI-Kit V3',
    'browserstack.local': true,
    'browserstack.video': true,
    'browserstack.console': 'errors',
    'browserstack.debug': false,
    'browserstack.networkLogs': false,
    'browserstack.appium_version': '1.13.0',
    nativeWebScreenshot: true,
    realMobile: true,
  },
  waitforTimeout: 10000
};
```
I am merging both configs and additionally browsers config and browser stack:
*Devices config*
```
module.exports = {
  capabilities: [
    {
      os_version: '12.1',
      device: 'iPhone XS'
    },
  ],
};
```
**Browser stack config**

```js
const browserstack = require('browserstack-local');

const localIdentifier = process.env.CI_JOB_ID || Date.now().toString();

exports.bs_local = new browserstack.Local();

module.exports = {
  services: ['browserstack'],
  browserstackLocal: true,
  onPrepare(config) {
    console.info('Connecting local');
    return new Promise((resolve, reject) => {
      exports.bs_local.start({ localIdentifier, key: config.key }, error => {
        if (error) {
          reject(error);
        } else {
          console.info('Connected. Now testing...');
          resolve();
        }
      });
    });
  },
  onComplete() {
    exports.bs_local.stop(() => {});
  },

  commonCapabilities: {
    build: localIdentifier,
    'browserstack.localIdentifier': localIdentifier,
  },
};
```
**Describe the bug**
When passing options to the checkFullPageScreen with the detail information about the folders options, the plugin is creating the screenshots in different folders and different name for the format image.

*checkFullScreen  Use**
```js
const testOptions = {
    autoSaveBaseline: true,
    baselineFolder: path.join(process.cwd(), `screenshots/reference/${kind}/${name}`),
    screenshotPath: path.join(process.cwd(), `screenshots/reference/${kind}/${name}`),
    savePerInstance: true,
    formatImageName: `{tag}-{platformName}-{browserName}-{width}x{height}`,
  };
  const results = browser.checkFullPageScreen('fullPage', {
    testOptions
  })
```
**To Reproduce**
Run the test with some local server or site with those capabilities and try to access call the method with options. I shared the browser stack capabilities, but actually the tests can be ran poiting up to any site.

**Expected behavior**
Plugin should generate the screenshots in the correct folder passed under the options

**Log**
```bash
#####################################################################################
 INFO:
 Autosaved the image to
 wic/baseline/fullPage-chrome-360x740-dpr-3.png
#####################################################################################

[0-0]
#####################################################################################
 INFO:
 Debug mode is enabled. Saved the debug file to:
 screenshots/errors/diff/fullPage-chrome-360x740-dpr-3.png
#####################################################################################

[0-0] PASSED in undefined - /test/visual/generated/generated1.js
[1-0]
#####################################################################################
 INFO:
 Autosaved the image to
 wic/baseline/fullPage-safari-375x812-dpr-3.png
#####################################################################################

[1-0]
#####################################################################################
 INFO:
 Debug mode is enabled. Saved the debug file to:
 screenshots/errors/diff/fullPage-safari-375x812-dpr-3.png
#####################################################################################


```
**Additional context**
Screenshots are being generated under the screenshots folder but not with the indicated name and additionally the baseline is being saved in wic folder the default. I dont share information detail of browser stack since the issue is specifically happing on the plugin side

**Comment by wswebcreation** [comment]
@gmontoya190 

Can you explain what you are expecting? I've ran checks here and I saw that the files are saved where they needed to be saved.

**Comment by gmontoya190** [comment]
@wswebcreation the files are not being generated in the correct folder. I do not see the files under this screenshots/reference/${kind}/${name}, they are saved as the log indicated ** wic/baseline/fullPage-safari-375x812-dpr-3.png**, and the image format is different too, supposed to be ```formatImageName: `{tag}-{platformName}-{browserName}-{width}x{height}`,``` but is using the default one.

**Comment by wswebcreation** [comment]
Ok, I'll get back to it, need to have some time to do the investigation.

**Comment by gmontoya190** [comment]
@wswebcreation did you have the chance to dig into it?

**Comment by wswebcreation** [comment]
@gmontoya190 

I've had time to look into it and to be honest, you are using the module in the wrong way.

- You are providing the plugin options to the test execution, that's incorrect usage, see the documentation for correct usage here https://github.com/wswebcreation/wdio-image-comparison-service/blob/master/docs/OPTIONS.md#plugin-options
- You are providing an object in an object 
  ```js
  const testOptions = {
    autoSaveBaseline: true,
    baselineFolder: path.join(process.cwd(), `screenshots/reference/${kind}/${name}`),
    screenshotPath: path.join(process.cwd(), `screenshots/reference/${kind}/${name}`),
    savePerInstance: true,
    formatImageName: `{tag}-{platformName}-{browserName}-{width}x{height}`,
  };
  const results = browser.checkFullPageScreen('fullPage', {
    testOptions
  })
  ```
  it should be `const results = browser.checkFullPageScreen('fullPage', testOptions)`
- You are providing the wrong options for changing the options per test execution. To use folder options per test, see https://github.com/wswebcreation/wdio-image-comparison-service/blob/master/docs/OPTIONS.md#folder-options

I'm going to close this issue because it's incorrect usage of the options
