### ISSUE TITLE
MultiRemote not supported

### ISSUE THREAD

**Issue by ericzered** [wswebcreation/wdio-image-comparison-service#28]
Hello,
I have an issue with multiremote and wdio-image-comparison-service : 
I'm using the service **'image-comparison'** without problem when I have only 1 browser, but when I run tests with multiremote, I have an error.

Example and repro:

In my wdio.conf.js I have this capabilities : 
```
exports.config = {
...
capabilities: [{ browserName: 'chrome' }],
...
}
```

in my spec file, I can do this without problem: 

```
browser.url('http://google.fr')
browser.saveScreen('examplePage')
```

But when I try to do multiremote like this : 

```
exports.config = {
...
capabilities: { chrome:{capabilities: { browserName: 'chrome' }},  firefox:{capabilities: { browserName: 'firefox' }}},
...
}
```

I can used the 'basic' wdio method like .url(), click().... but not the services.
So this : 
```
browser['chrome'].url('http://google.fr')
browser['firefox'].url('http://bing.com')
browser['chrome'].saveScreen('examplePage')
```
opens Chrome and Firefox, goes to excepted url but just after give me this error : 

> ERROR @wdio/sync: TypeError: Cannot read property 'browserName' of undefined
>     at getInstanceData (/Users/user/Work/Git/QATestAuto/node_modules/wdio-image-comparison-service/build/utils.js:45:72)
>     at WdioImageComparisonService.before (/Usersuser/Work/Git/QATestAuto/node_modules/wdio-image-comparison-service/build/service.js:43:53)
>     at execHook (/Users/user/Work/Git/QATestAuto/node_modules/@wdio/sync/build/executeHooksWithArgs.js:46:23)
> browser.chrome.saveScreen is not a function

(I've tried to use browsername like chrome.saveScreen() with the same result)

**Environment (please complete the following information):**
 - Node.js version: 11.14.0
 - NPM version: 6.9.0
 - Browser name and version: all browsers
 - Platform name and version: [e.g. Windows 10]
 - WebdriverIO version: 5.10.4
 - wdio-image-comparison-service version: 1.12.1

Thanks !

**Comment by wswebcreation** [comment]
The module doesn't support multiremote so it will be a feature. Will add it on my todo list

**Comment by ericzered** [comment]
Thank you :)

**Comment by wswebcreation** [comment]
@ericzered 

I looked into this one and I can't get it working for now. The multiremote session works different in comparison to a _single_-session. Both browser are now run in the same session and I don't have access to the capabilities, making this harder to use and determine the correct data.

I need to dive into it more, but because multi-remote is not the biggest feature / has the highest usage I will give it a lower priority

**Comment by ericzered** [comment]
thanks, that's fair, thanks for the hard work :)

**Comment by pip8786** [comment]
@ericzered I have opened a PR for this: https://github.com/wswebcreation/wdio-image-comparison-service/pull/60.

**Comment by ericzered** [comment]
@pip8786 that so cool, I'm still really interested !
Thanks a lot :)

**Comment by wswebcreation** [comment]
A new version has been released, see https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v2.2.0

Thanks @pip8786 !!!
