### ISSUE TITLE
Allow commands to accept a folder options object

### ISSUE THREAD

**Issue by rundmd** [wswebcreation/wdio-image-comparison-service#3]
**Problem**
The folder locations cannot be set dynamically and doesn't allow us to save screenshots underneath each of our component directories. We can use the wdio options object to set the paths when running specs individually, but not when running a suite of tests

**Solution**
Allowing each command to accept a folders object allows users to use the mocha test context to figure out test names and locations and create the proper folder paths for the baseline, actual, and diff screenshots:
```
describe('Example Test', function () {
  it('should test something', function() {
    const descr = getDescription(this);
    const folders = getFolders(this)
    expect(browser.checkFullPageScreen(descr, {}, folders)).to.equal(0);
```

**Comment by rundmd** [comment]
I will submit a PR later today

**Comment by wswebcreation** [comment]
👍🏻

**Comment by wswebcreation** [comment]
https://github.com/wswebcreation/wdio-image-comparison-service/pull/4

**Comment by wswebcreation** [comment]
@rundmd 

I've release `1.3.0` with your feature, thanks for that. Can you verify that it works and then close the issue if you want?
