### ISSUE TITLE
V6 support

### ISSUE THREAD

**Issue by ryuran** [wswebcreation/wdio-image-comparison-service#33]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/wswebcreation/wdio-image-comparison-service) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
The current version seems not compatible with webdriverio v6.
It's not noticed in readme.

**Comment by anto-ac** [comment]
It is compatible. I’m using it.

**Comment by wswebcreation** [comment]
Yep, it is compatible with V6, closing it for now because there is also no logs or description what the problem is

**Comment by ryuran** [comment]
Do we have an example? @anto-ac @wswebcreation
I have some issue to integrate it.

**Comment by anto-ac** [comment]
What are the issues?
