### ISSUE TITLE
Disabled elements on the page should not be tabbed

### ISSUE THREAD

**Issue by jacknjill02** [wswebcreation/wdio-image-comparison-service#34]
**Environment (please complete the following information):**
 - Node.js version: 10.17.0
 - NPM version: 6.11.3
 - Browser name and version:Chrome 81
 - Platform name and version: macOS 10.13.6
 - WebdriverIO version: 5.18.7
 - wdio-image-comparison-service version: 1.12.2

**Config of WebdriverIO + wdio-image-comparison-service**
An example of how you configured the wdio-image-comparison-service

wdio.conf.js file has following service
 services: [ 'chromedriver',
        ['image-comparison', 
        {
            // Some options, see the docs for more
            baselineFolder: join(process.cwd(), './tests/baseline/'),
            formatImageName: 'test-chrome',
            screenshotPath: join(process.cwd(), '.tmp/'),
            savePerInstance: true,
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutToolBar: true,
                 tabbableOptions: {
                       circle: {
                           size: 18,
                           fontSize: 18,
                          showNumber: true
                       },
                      line: {
                      color: '#ff221a',
                      width: 3
                      }
                 }
           }], 
      ],

**Describe the bug**
While using browser.checkTabbablePage('tabbable') method, if some of the elements on the page are disabled, then tabbing should not happen on the disabled elements and the order of tabbing with lines and circles should be done only with enabled elements. In the screenshot below, Tab circle (5) should have been skipped.  

![a11y-tab-sequence](https://user-images.githubusercontent.com/46605200/79472180-21c60100-7fc9-11ea-8222-3581e60afe55.png)

**To Reproduce**

1. Visit on the saucelabs url:

- browser.url('https://accounts.saucelabs.com/am/XUI/?region=us-west-1#login/')

2. Then click on the "Sign In" button with no username and password:

- $('//*[@id="loginButton_0"]').click();

3. "Sign In" button is disabled and now run  tabbing method.

- browser.checkTabbablePage('tabbable')

**Expected behavior**
There should not have been a tabbing on the "Sign In" button since the button was disabled.

**Comment by wswebcreation** [comment]
@jacknjill02 

I've released a new version, can you check it with version https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.13.0 and close it if it is fixed?

**Comment by wswebcreation** [comment]
I'll close it now because as far as I can see it's fixed
