### ISSUE TITLE
Multiple element selector only hiding first match

### ISSUE THREAD

**Issue by kevinlacotaco** [wswebcreation/wdio-image-comparison-service#35]
**Describe your question with as much detail as possible**

Hiding only one of the elements matching a selector when updating to puppeteer. It seems the removal/hidden elements is passed through all the way to the client script but I have been having trouble debugging where exactly it might break. My question is basically do I need to debug a visual Chrome execution to get access to the client script logic?

My selector is something like `browser.$$('[data-thing="MULTIPLE"]')` and I make sure they are all displayable elements before sending them in. When in puppeteer we are getting `HTMLElement`s or are they still `WebElement`s?

**If it's about a specific piece of code, try and include some of it to support your question.**

https://github.com/wswebcreation/webdriver-image-comparison/blob/master/lib/clientSideScripts/hideRemoveElements.ts#L30

**Environment (please complete the following information):**
 - Node.js version: 10.16.3
 - NPM version: locally: 6.14.4, docker: 6.9.0
 - Browser name and version: locally: Chrome 81.0.4044.113, docker: Chrome 79 
 - Platform name and version: locally: OSX, docker: linux
 - WebdriverIO version: 6.1.0
 - wdio-image-comparison-service version: 1.13.0

**Additional context**

**Comment by wswebcreation** [comment]
Thanks for filing an issue, I'll take a look at it in the coming days

**Comment by wswebcreation** [comment]
Hi @kevinlacotaco 

I've been checking this with this version:

```js
  "devDependencies": {
    "@wdio/cli": "^6.1.3",
    "@wdio/devtools-service": "^6.0.16",
    "@wdio/jasmine-framework": "^6.1.3",
    "@wdio/local-runner": "^6.1.3",
    "@wdio/spec-reporter": "^6.0.16",
    "@wdio/sync": "^6.1.0",
    "devtools": "^6.1.3",
    "webdriverio": "^6.1.3",
    "webdriver-image-comparison": "0.14.1"
  },
```

and this script

```js
    describe('compare screen', () => {
        it('should compare successful with a baseline', () => {
            browser.url('https://www.saucelabs.com')
            browser.saveScreen('with-links-hl')
            browser.saveScreen('wihtout-links-hl', {
                hideElements: [$$(('.link'))],
            })
        });
    });
```

And this is the result, first image without hiding the elements, with-links-hl
![with-links-hl-chrome-dev-tools-headless-1366x768](https://user-images.githubusercontent.com/11979740/80302504-c0f9ae00-87aa-11ea-84f8-bf9a6b9b86f1.png)

And the second image with hiding the links
![wihtout-links-hl-chrome-dev-tools-headless-1366x768](https://user-images.githubusercontent.com/11979740/80302513-cb1bac80-87aa-11ea-8022-217a89fd5003.png)

It looks ok, can you check with the latest versions? If it still is a problem, can you provide a repo with a reproducible example?

**Comment by kevinlacotaco** [comment]
Ok, let me try to get a reproducible example. I am wondering if its due to `[data-x]` attributes instead of classes?

**Comment by kevinlacotaco** [comment]
I threw this together: https://github.com/wswebcreation/webdriver-image-comparison/pull/68 which seems to have solved my issue.

**Comment by wswebcreation** [comment]
Should be fixed now with https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.13.2
