### ISSUE TITLE
browser.checkElement function captures someother image instead of element image

### ISSUE THREAD

**Issue by NirmalAyyappan** [wswebcreation/wdio-image-comparison-service#36]
I am new to WDIO, just exploring the features for WDIO - visual testing. I tried to do visual comparison of an element ["..pluginRowBlock"] on WDIO page. 
The baseline image of the element which is stored under .tmp folder is something else not the screenshot of the .pluginRowBlock [expected: image contains getstarted ,watch talk etc] actual image in tmp folder is doc,api,help that whole section.

Sorry i am not able upload the screenshot:(

here is my code

```js
describe('Visual test',()=>{
    it('Verify visual of webdriver IO page',()=>{
    // Check a screen
    browser.url('https://webdriver.io');
    //expect(browser.checkScreen('examplePaged')).toEqual(0);
    const title = browser.getTitle();
    assert.strictEqual(title, 'WebdriverIO · Next-gen browser automation test framework for Node.js');
    //assert.equal(browser.checkScreen('examplePaged'),0,"Home page is not matching with baseline"); 
   
    assert.equal(browser.checkElement($(".pluginRowBlock"),'rowblock'),0,"row block is not matching with baseline");    
    });
}); 

```

**Comment by wswebcreation** [comment]
Hi @NirmalAyyappan 

thanks for filing an issue, I've tried it and it just works. Can you provide the images by just dragging them into the comment field on GitHub when you add a new comment to this issue?

**Comment by NirmalAyyappan** [comment]
Hi, 

thanks for the response.

I have attached actual image which taken for baseline.
![rowblock_actual](https://user-images.githubusercontent.com/7247646/80384789-f1cd0680-88c2-11ea-8c53-4459f965f018.jpg)

But expected image for the object is 
![expected_rowblock](https://user-images.githubusercontent.com/7247646/80384948-22ad3b80-88c3-11ea-8518-c36c52a3068d.png)

**Comment by wswebcreation** [comment]
Hi @NirmalAyyappan 

Can you provide the setup and screenresolution? It looks like your screen is smaller and needs to scroll to the element before taking the screenshot.

**Comment by NirmalAyyappan** [comment]
I have followed setup document given in webdriverio and the command used to download dependencies "npm install --save-dev wdio-image-comparison-service".

OS: Windows 10
Screen resolution: 1920*1080.

Thanks for the timely response. 
I will check in the large screen or by changing the screen resolution.

**Comment by wswebcreation** [comment]
Hi @NirmalAyyappan 

Did you made any progress here?

**Comment by NirmalAyyappan** [comment]
Nope, i couldn't check as i don't have larger screen monitor with me.
I will check in different screen resolution and reopen this issue if i face the same.

thank you so much of your support.
