### ISSUE TITLE
Block Out Element by selector

### ISSUE THREAD

**Issue by smichaelsen** [wswebcreation/wdio-image-comparison-service#38]
`checkElement()` has a `blockOut` Option that can define an area that is ignored for the image comparison. It only accepts absolute coordinates. However when testing across multiple screen sizes and browsers we can not rely on absolute coordinates that are hardcoded in our test. Is there any possibility to determine the coordinates of a given element during runtime?

I've seen there is a `determineElementRectangles` method in the TypeScript source that does exactly that. Is it accessible somehow for me as a test writer?

**Comment by wswebcreation** [comment]
Hi @smichaelsen 

Currently it's not supported, it's a feature. I need to think about how to implement this because it should be used for all functions. I'll add it to my todo list

**Comment by smichaelsen** [comment]
I solved it for us:

````
browser.execute((parentElement, childElement) => {
    var parentPos = parentElement.getBoundingClientRect();
    var childPos = childElement.getBoundingClientRect();
    return {
        height: Math.round(childPos.height),
        width: Math.round(childPos.width),
        x: Math.round(childPos.left - parentPos.left),
        y: Math.round(childPos.top - parentPos.top),
    };
}, parentElement, childElement);
````

This returns the coordinates of a child element relative to the given parent, in the structure that is needed for `blockOut`.

**Comment by wswebcreation** [comment]
Awesome, thanks for posting it here
