### ISSUE TITLE
Check Element that is bigger than the viewport

### ISSUE THREAD

**Issue by smichaelsen** [wswebcreation/wdio-image-comparison-service#39]
When using `checkElement()` on an Element that has more height than the current viewport (think of a long webform) the resulting screenshot has a top area with the visible part of the element and the rest of it is just transparent.
Is there a way to test large elements without taking a full page screenshot?

<img width="398" alt="Screenshot 2020-05-04 at 21 23 45" src="https://user-images.githubusercontent.com/912435/81004999-8ef0e780-8e4d-11ea-850d-c1df445e1fd6.png">

**Comment by wswebcreation** [comment]
@smichaelsen 

Closing this one because the work needs to be done [here](https://github.com/wswebcreation/webdriver-image-comparison) and there is already a ticket open, see https://github.com/wswebcreation/webdriver-image-comparison/issues/20

For now you're stuck with a fullpage screenshot

**Comment by smichaelsen** [comment]
Thanks for the pointer
