### ISSUE TITLE
Version 1.13 includes breaking changes

### ISSUE THREAD

**Issue by colinrotherham** [wswebcreation/wdio-image-comparison-service#40]
**Environment (please complete the following information):**
 - Node.js version: 8.17.0
 - NPM version: 6.13.4
 - Browser name and version: N/A
 - Platform name and version: N/A
 - WebdriverIO version: 5.22.4
 - wdio-image-comparison-service version: 1.13.3

**Describe the bug**
I can see during install on Node.js 8 that various unsupported breaking changes have been introduced since 1.12. I've had to temporarily pin the older version.

During install on Node.js 8:

```
npm WARN notsup Unsupported engine for fs-extra@9.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: fs-extra@9.0.0
npm WARN notsup Unsupported engine for chalk@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: chalk@4.0.0
npm WARN notsup Unsupported engine for universalify@1.0.0: wanted: {"node":">= 10.0.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: universalify@1.0.0
```

When running the tool on Node.js 8:

```
2020-05-06T13:40:24.127Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
/Users/colin/Sites/Co-op/membership-website-tests/node_modules/webdriver-image-comparison/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^
```

I can see Node.js 8 and 10 are missing from your Travis tests:  
https://github.com/wswebcreation/wdio-image-comparison-service/blob/master/.travis.yml#L6

**To Reproduce**

Upgrade to **wdio-image-comparison-service@1.13** and run it on Node.js 8.

**Expected behavior**
As this upgrade is a minor release (not a major version) it should continue to work in Node.js 8, otherwise the version number should become `2.0.0`, sorry!

The readme still says:

>wdio-image-comparison-service supports NodeJS 8 or higher

Thanks for taking a look at this.

**Comment by wswebcreation** [comment]
@colinrotherham 

Thanks for the ticket, I never thought about NodeJS 8, was assuming that people would not use it anymore because it's not supported anymore.

I've installed NodeJS 8 on my machine and when I install the project I don't get the error. Which version of NodeJS 8 are you using?

This was my log

![image](https://user-images.githubusercontent.com/11979740/81192588-bb764200-8fba-11ea-854b-bf7f480ba1fd.png)

**Comment by colinrotherham** [comment]
@wswebcreation Sorry no, it's completely broken on Node.js 8 😭

Anyone else on Node.js 8 that runs `npm install` or `npm update` will also pull in the unsupported breaking changes from **fs-extra**, **chalk** and **universalify** packaged with the `v1.13` releases.

Ideally all `v1.13` releases should be marked as deprecated and a new `v2.0` release added, otherwise anyone else on Node.js 8 will automatically roll onto the new packages via _semver_ too.

```bash
wdio-image-comparison-service@1.12.0 # Node.js 8+
wdio-image-comparison-service@1.12.1 # Node.js 8+
wdio-image-comparison-service@1.12.2 # Node.js 8+

wdio-image-comparison-service@1.13.0 # deprecated!
wdio-image-comparison-service@1.13.1 # deprecated!
wdio-image-comparison-service@1.13.2 # deprecated!
wdio-image-comparison-service@1.13.3 # deprecated!

wdio-image-comparison-service@2.0.0 # Node.js 10+
```

We're aiming to move off Node.js 8, and we're happy to stay on `v1.12` for a while.

If anyone else has this problem you'll need to pin the install to prevent updates, but `npm outdated` will still flag `v1.13` as an available minor release.

```bash
npm install wdio-image-comparison-service@1.12 --save-exact
```

**Comment by wswebcreation** [comment]
Hi @colinrotherham 

Because it's not a breaking change for everybody (at least from what I hear and see) I didn't release a V2, but created a patch that fixes this, see https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.13.4

Reason for this is also that you will now have all the latest fixes of the core, with NodeJS 8 support. I've tried it on my machine and I didn't got any errors. Can you also verify it on your machine and if it is fixed close this issue?

**Comment by colinrotherham** [comment]
@wswebcreation That's great, it's all working again now 🎉 

Can you [npm deprecate](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions) the ones that didn't work with Node 8 just in case anyone else tries to install them? Then if you need to bump them back up again start version `2.0.0` 😊 

Thanks again
