### ISSUE TITLE
hideAfterFirstScroll giving error in typescript Spec

### ISSUE THREAD

**Issue by amitAutoS** [wswebcreation/wdio-image-comparison-service#43]
Trying to use hideAfterFirstScroll in checkFullPageScreen method but it's giving error: 
**TS2740: Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 230 more.**

`expect(browser.checkFullPageScreen(this.test.title,{hideAfterFirstScroll: [$('#privacy-information')]} )).equal(0);`

- TypeScript
 - Node.js version: [v12.13.1]
 - NPM version: [6.12.1]
 - Browser name and version: [NA] - compiler issue
 - Platform name and version: [NA] - compiler issue
 - WebdriverIO version: [5.14.0]
 - wdio-image-comparison-service version: [0.14.4]

**Comment by wswebcreation** [comment]
Thanks for the issue @amitAutoS 

Can you provide a reproducible example in a git repo so I can check the error

**Comment by amitAutoS** [comment]
Its internal org code, so cant put it outside and would need some time to prepare reproducing example.
In the mean time, what I think is, hideAfterFirstScroll is expecting HTMLElement. When I looked up in the code in fullPage.interfaces.d.ts
`hideAfterFirstScroll?: HTMLElement[];`

When I use this LOC in my code, it is passing Element type
`expect(browser.checkFullPageScreen(this.test.title,{hideAfterFirstScroll: [$('#privacy-information')]} )).equal(0);`

What do you reckon?

**Comment by amitAutoS** [comment]
@wswebcreation Here's the sample project for the issue:
https://github.com/amitAutoS/WebdriverIO_v5_TypeScript

Pls refer login.spec.ts and check for this testcase _should compare successful with a baseline_

**Comment by wswebcreation** [comment]
Tnx,

I have some time tomorrow and then I'll take a look at it

**Comment by wswebcreation** [comment]
@amitAutoS 

Should be fixed with https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v1.13.6, tested it with your project. Closing it for now
