### ISSUE TITLE
Screen comparison for iPad(landscape) not fully ignoring address bar

### ISSUE THREAD

**Issue by stwippie** [wswebcreation/wdio-image-comparison-service#45]
**Environment (please complete the following information):**
 - Node.js version: [v12.16.1]
 - NPM version: [6.13.4]
 - Browser name and version: [Safari 12]
 - Platform name and version: [Browserstack iPad Air 2019]
 - WebdriverIO version: [6.1.22]
 - wdio-image-comparison-service version: [1.13.6]

**Config of WebdriverIO + wdio-image-comparison-service**

```
baselineFolder: path.resolve("./", "wdio-tests/screenshots/real-devices/reference"),
            screenshotPath: path.resolve("./", "wdio-tests/screenshots/real-devices/taken"),
            blockOutStatusBar: true,
            blockOutToolBar: true,
            savePerInstance: true,
            autoSaveBaseline: true,
            returnAllCompareData: true,
            formatImageName: "{tag}-{browserName}",
```

```
var capabilities = {
'bstack:options' : {
"osVersion" : "12",
"deviceName" : "iPad Air 2019",
"realMobile" : "true",
"appiumVersion" : "1.14.0",
"local" : "true",
"deviceOrientation" : "landscape",
},
"browserName" : "iPad",
}
```

**Describe the bug**
When run image comparison against iPad landscape a status bar and an address bar are not fully ignored. And it looks like ignored part are taken as for portrait orientation. 
![ipad_air_2019-12-landscape](https://user-images.githubusercontent.com/4716446/87942614-88195e80-caa5-11ea-8c66-ca46304841c3.png)

Issue not reproducible with portrait orientaion.

**Expected behavior**
fully ignored status bar and address bar for tablet landscape orientation

**Log**

**Additional context**

**Comment by wswebcreation** [comment]
Thanks for filling the issue. This is a know bug to me, the core module currently doesn't support this for Landscape mode. I need to take a look at it and try to fix it, but with the upcoming holiday don't expect it to be fixed in a few days 😉

**Comment by Apxu** [comment]
Hello @wswebcreation do you have any updates here?

**Comment by wswebcreation** [comment]
Hi @Apxu 

No, not yet, but any help would be appreciated

**Comment by wswebcreation** [comment]
This will be fixed by this PR https://github.com/wswebcreation/wdio-image-comparison-service/pull/93
