### ISSUE TITLE
Add log level option

### ISSUE THREAD

**Issue by tenjerma** [wswebcreation/wdio-image-comparison-service#46]
I use this service in a bit of an unorthodox way, basically as a verification step before and after a test, where a baseline is generated before the step and the affected element is checked after some actions are executed after a step. The problem is I don't have a preset of baselines, but rather they are generated on every run. This causes the terminal to be spammed with "INFO:" logs.

A log level option that disables these logs OR a log level option that allows control of various types of levels: [verbose, normal, error, disabled]

![image](https://user-images.githubusercontent.com/19725595/94476874-efc6e680-0185-11eb-8874-cc07be8298a9.png)

**Comment by wswebcreation** [comment]
Sorry for my late response, I'll take a look at it in the coming weeks but if you want to open a PR then feel free to do so

**Comment by wswebcreation** [comment]
@tenjerma 

This will implement it

**Comment by tenjerma** [comment]
@wswebcreation PR to update the dependency in `wdio-image-comparison-service`: https://github.com/wswebcreation/wdio-image-comparison-service/pull/47

**Comment by wswebcreation** [comment]
Hi @tenjerma 

Closing yours in favour of this one https://github.com/wswebcreation/wdio-image-comparison-service/pull/48 because there are _breaking_ changes due to the removal of support for Node.js 8

**Comment by wswebcreation** [comment]
@tenjerma 

I've released https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v2.0.0
