### ISSUE TITLE
Backstop-like reporter for the service

### ISSUE THREAD

**Issue by orandzheviyman** [wswebcreation/wdio-image-comparison-service#49]
Used the BackstopJS for a long time and then switched to the wdio-image-comparison-service
It is excellent, but I really miss a reporter in which it would be convenient and quick to see the changes in the layout. it seems to me how the BackstopJS was done would be very suitable here too.
Or already exist reporter like BackstopJS for wdio-image-comparison-service? I will be grateful for the links

**Environment:**
 - Node.js version: 13.11
 - NPM version: 7.0.11
 - Browser name and version: any
 - Platform name and version: Win 10
 - WebdriverIO version: 6.6.2
 - wdio-image-comparison-service version: 1.13.6

**Comment by wswebcreation** [comment]
Hi @orandzheviyman 

Thanks for your request. I'd like to keep this module as _simple_ as possible and don't have this on my future roadmap. Maybe you can create a module on top of this module that does the Backstop magic.

Going to close it for now, but it's still open for discussion
