### ISSUE TITLE
Use test name as screenshot file name?

### ISSUE THREAD

**Issue by alisman** [wswebcreation/wdio-image-comparison-service#50]
In an earlier version of WDIO (wdio-visual-regression-service), the framework could pick up the name of the test 

` it(THIS_THING, ()=>test)`

as the name of the screenshot. This was super helpful because it allowed us to easily get from test report back to test spec with code search.

Is there any simple way to achieve this in the new service?

**Comment by wswebcreation** [comment]
Hi @alisman 

Thanks for your issue. This is not a rewrite of the `wdio-visual-regression-service`, but a completely different module. Feel free to open a PR for this

**Comment by sytolk** [comment]
@alisman to get test name you can write 
```
const filename = `${expect.getState().currentTestName}.png`;
```
but how can we use this service to get screenshot [running programmatically](https://github.com/wswebcreation/wdio-image-comparison-service#running-programmatically)?
this miss me:
```
wdioImageComparisonService.afterTest(() => takeScreenshot());
```

**Comment by zbyte64** [comment]
Here's how I did it without rewriting all my tests to invoke such an awkward pattern.

In your wdio.conf.js:

```javascript
const {default: WdioImageComparisonService} = require('wdio-image-comparison-service');

export.config = {
// your wdio config
// add a mocha hook to reregister the browser commands but with a format that includes the test name
async beforeTest(test) {
    const testName = test.title // may want to include test.parent
    // prefix image snapshots with test name
    const imageService = new WdioImageComparisonService({
      ...imageComparisonOptions,
      formatImageName: `${testName}.{tag}`,
    })
    const capabilities = [
      {
        browserName: 'chrome'
      }
    ];
    imageService.addCommandsToBrowser(capabilities, browser)
    }
  }
```
