### ISSUE TITLE
Retries of test deletes all actual folder images

### ISSUE THREAD

**Issue by AutomationGuru** [wswebcreation/wdio-image-comparison-service#52]
**Environment (please complete the following information):**
Node.js version: 14.5.0
NPM version: 6.14.5
Browser name and version: Chrome 87
Platform name and version: mac
WebdriverIO version: 6.10.11
wdio-image-comparison-service version: 2.0.0

```js
const config = {

user: process.env.BROWSERSTACK_USER,
key: process.env.BROWSERSTACK_KEY,

services: [
['image-comparison',
// The options
{
baselineFolder: BASELINE_IMAGE_FOLDER,
formatImageName: '{tag}-{logName}-{width}x{height}',
screenshotPath: ALL_IMAGE_FOLDER,
savePerInstance: true,
autoSaveBaseline: true,
blockOutStatusBar: true,
blockOutToolBar: true,
clearRuntimeFolder: true,
},
],
],

exclude: [
],
specs: [
'./tests/**/*.spec.js',
],
specFileRetries: 2,

maxInstances: 50,

capabilities: [
{
browserName: 'chrome',
browser_version: '87',
os: 'OS X',
os_version: 'Catalina',
acceptInsecureCerts: true,
resolution: '1280x960',
realMobile: false,
local: false,
buildName: buildDescription,
projectBrowserName: SCREEN_SIZE.DESKTOP.type,
projectName,
},
{
browserName: 'chrome',
'goog:chromeOptions': {
mobileEmulation: { deviceName: 'iPhone X' },
},
browser_version: '87',
os: 'OS X',
os_version: 'Catalina',
acceptInsecureCerts: true,
resolution: '1280x960',
realMobile: false,
local: false,
buildName: buildDescription,
projectBrowserName: SCREEN_SIZE.IPHONE_X.type,
projectName,
},
],
logLevel: 'error',

bail: 0,

baseUrl: 'http://localhost:3000',
waitforTimeout: 20000,
connectionRetryTimeout: 120000,
connectionRetryCount: 3,

framework: 'mocha',
reporters: ['spec',
['junit', {
outputDir: JUNIT_REPORTS,
outputFileFormat() { // optional
return 'visualTestRuns.xml';
},
}],
],

mochaOpts: {
// Babel setup
compilers: ['js:@babel/register'],
ui: 'bdd',
timeout: 900000,
}
beforeSession(config, capabilities, specs) { // eslint-disable-line
global.assert = chai.assert;
},
};
````

**Describe the bug**

Given i run visual test runs using webdriverIO and image comparison library on browserstack or locally and parallel to each test runs ( ~50 runs at once)
when any test spec fails, 
then i notice all the screenshots from the actual folder are deleted

**To Reproduce**
Use the config above to get one of two test to fail and check the actual folder 

**Expected behavior**
Expected only the test specific screenshot to be deleted or the actual folder backed up as i cannot view was was test verified against ?

**Log**

**Additional context**

**Comment by wswebcreation** [comment]
Hi @AutomationGuru 

You've enabled `clearRuntimeFolder `, see https://github.com/wswebcreation/webdriver-image-comparison/blob/master/docs/OPTIONS.md#clearruntimefolder. This means that if the module, when it is instantiated for the first, second or nth time will clean the folder. In combination with `specFileRetries`, which you have in the config, the module is being instantiated again and the folder will be cleaned. This is the way how WebdriverIO works and is not something that I can help.
Feel free to open an issue on the WebdriverIO project or check in their Gitter channel. Going to close it

**Comment by AutomationGuru** [comment]
Thanks again for looking my bad removed that and works fine
