### ISSUE TITLE
Question: Trying to get this working in blueimp/wdio/ containerized project

### ISSUE THREAD

**Issue by kumarpatel** [wswebcreation/wdio-image-comparison-service#6]
Wondering if you can either help out or have any insight into this problem.
Any help would be appreciated.

Running into issues when integrating this service into [this containerized wdio project](https://github.com/blueimp/wdio)

You can read more about issue (error snippet, etc) here
https://github.com/blueimp/wdio/issues/9

Have you looked into Dockerization at all?

**Environment (please complete the following information):**
 - Node.js version: v10.16.0
 - NPM version: 6.10.0
 - Browser name and version: N/A
 - Platform name and version: alpine:3.10
 - WebdriverIO version: 5.11.2
 - wdio-image-comparison-service version: Trying to install the latest version. (npm install -g wdio-image-comparison-service)

Thanks in advance.

**Comment by wswebcreation** [comment]
Hi @kumarpatel 

No I haven't looked into docker support for this module at all, and I must say I haven't seen this issue before. Have you already checked Google? I directed me to this thread https://github.com/mapbox/node-pre-gyp/issues/364#issuecomment-456638826.

Hope it helps
