### ISSUE TITLE
nativeWebScreenshot capability doesn't work when using webdriverIO v7

### ISSUE THREAD

**Issue by vuhuykhanh** [wswebcreation/wdio-image-comparison-service#61]
**Environment **
 - Node.js version: [e.g. 14.15.0]
 - NPM version: [e.g. 6.14.8]
 - Browser name and version: [e.g. Chrome 83]
 - Platform name and version: [e.g. Android]
 - WebdriverIO version: [e.g. 7.1.2]
 - wdio-image-comparison-service version: [e.g. 2.2.0]

**Config of WebdriverIO + wdio-image-comparison-service**
An example of how you configured the wdio-image-comparison-service
v6 webdriverIO wdio.conf.js

```js
  capabilities: [
    {
      maxInstances: 1,
      platformName: "Android",
      "appium:deviceName": process.env.DEVICE_NAME || "Nexus 6",
      browserName: process.env.BROWSER_NAME || "chrome",
      "appium:platformVersion": process.env.PLATFORM_VERSION || "11.0",
      "appium:orientation": "PORTRAIT",
      "appium:automationName": "UiAutomator2",
      "appium:newCommandTimeout": 180000,
      "appium:autoWebview": false,
      nativeWebScreenshot: true
    },
  ],
```
v7 webdriverIO wdio.conf.js
```js
  capabilities: [
    {
      maxInstances: 1,
      platformName: "Android",
      "appium:deviceName": process.env.DEVICE_NAME || "Nexus 6",
      browserName: process.env.BROWSER_NAME || "chrome",
      "appium:platformVersion": process.env.PLATFORM_VERSION || "11.0",
      "appium:orientation": "PORTRAIT",
      "appium:automationName": "UiAutomator2",
      "appium:newCommandTimeout": 180000,
      "appium:autoWebview": false,
      "appium:nativeWebScreenshot": true
    },
  ],
```
**Describe the bug**
At v6 of webdriverIO, the nativeWebScreenshot capability works fine but when I upgrade to v7, it returns an error like in the picture
<img width="1066" alt="Screen Shot 2021-03-25 at 9 55 59 AM" src="https://user-images.githubusercontent.com/32718095/112413728-49822500-8d53-11eb-93a7-ed8f37b850f3.png">

So I try to add a prefix "appium:" and it worked but the screenshot was taken duplicate

<img width="165" alt="Screen Shot 2021-03-25 at 10 27 17 AM" src="https://user-images.githubusercontent.com/32718095/112414556-d1b4fa00-8d54-11eb-9cf2-7b78ded80c6f.png">

The screenshot should be like this

<img width="332" alt="Screen Shot 2021-03-25 at 10 27 50 AM" src="https://user-images.githubusercontent.com/32718095/112414653-fb6e2100-8d54-11eb-8f36-7f7552cebfdf.png">

[Include code or an example repository that can easily be set up]
I've checked the source code of wdio-image-comparison-service and find these codes 
`const nativeWebScreenshot = !!capabilities.nativeWebScreenshot`
I tried changing it to this and it worked
`const nativeWebScreenshot = !!capabilities["appium:nativeWebScreenshot"]`  and it worked

**Expected behavior**
Should include "nativeWebScreenshot" capability support for v7 of webdriverIO

**Comment by wswebcreation** [comment]
@vuhuykhanh 

Thanks for filling the issue and also looking into the rootcause. I need to fix [this line](https://github.com/wswebcreation/wdio-image-comparison-service/blob/f57b66370bf9e3e76e7f57f15cd5b76db8a8c6ca/lib/utils.js#L53) for being compatible with W3C.
Feel free to open a PR, otherwise it will be tomorrow from my side I think

**Comment by wswebcreation** [comment]
@vuhuykhanh 

I've released version https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v2.2.1

**Comment by vuhuykhanh** [comment]
@wswebcreation ws
Thank you for your quick response !
