### ISSUE TITLE
Diff images are not getting generated with programetic usage

### ISSUE THREAD

**Issue by abhinaba-ghosh** [wswebcreation/wdio-image-comparison-service#64]
My programmatic configuration 

```
const WdioImageComparisonService = require('wdio-image-comparison-service')
  .default;
const wdioImageComparisonService = new WdioImageComparisonService({});

const _folders={                                                        
  actualFolder: 'test-reports/visual-regression/actual/',
  baselineFolder: 'test/test-data/visual-regression/baseline/',
  diffFolder: 'test-reports/visual-regression/diff/'
}

const _optins={
 formatImageName: '{tag}-{logName}-{width}x{height}',
  savePerInstance: true,
  autoSaveBaseline: true,
  clearRuntimeFolder: true,
  blockOutStatusBar: false,
  blockOutToolBar: false,
  isHybridApp: false,
}

  wdioImageComparisonService.folders = _folders
  wdioImageComparisonService.defaultOptions =_options;

  browser.defaultOptions = wdioImageComparisonService.defaultOptions;
  browser.folders = wdioImageComparisonService.folders;

  wdioImageComparisonService.before(browser.capabilities);

```

after running a test I am getting `diff` result in the console as:
```
Error: expect(received).toEqual(expected) // deep equality

Expected: 0
Received: 0.33
```

Although the `baseLine` and `actual` images are getting stored in specified paths `diff` images are not getting generated and stored.

**Comment by wswebcreation** [comment]
Hi @abhinaba-ghosh 
Thanks for filing a ticket, which version of the module are you using?

**Comment by abhinaba-ghosh** [comment]
@wswebcreation Here it is:

```
 "wdio-image-comparison-service": "^2.3.0",
 "@wdio/local-runner": "^6.4.0",
 "@wdio/mocha-framework": "^6.4.0",
 "@wdio/sync": "^6.4.0",
```
```
Mac Big Sur
v11.2.3 
```

**Comment by wswebcreation** [comment]
Hi @abhinaba-ghosh 

I've been running this project and adjusted this testcase https://github.com/wswebcreation/wdio-image-comparison-service/blob/master/tests/specs/checkMethodsFolders.spec.js#L31

I've added this line `browser.execute('arguments[0].innerHTML = "Test Demo Page";', $('h1.uk-heading-large'));` on line 39, before the check is being executed and it's creating the folder, see the image

![image](https://user-images.githubusercontent.com/11979740/114553822-56b17600-9c66-11eb-9735-13048f00a450.png)

Can you provide a reproducible example?

**Comment by abhinaba-ghosh** [comment]
@wswebcreation I think this is still not a programmatic usage. Can you let me know how to use custom folder paths for actual, baseline and diff  here:
https://webdriver.io/docs/wdio-image-comparison-service/#running-programmatically

**Comment by wswebcreation** [comment]
I need to dig into this @abhinaba-ghosh but don't have the time for it today. Any help from someone else would be appreciated

**Comment by wswebcreation** [comment]
Closing this one due to inactivity. Feel free to reopen or create a new issue

**Comment by rijojon121** [comment]
am having the same issue diff image is not showing up , is the above resolved thanks,
