### ISSUE TITLE
Issues with Chrome 90

### ISSUE THREAD

**Issue by zarko-tg** [wswebcreation/wdio-image-comparison-service#66]
Now that Chrome 90 stable is out some of our visual regression tests started to fail (diffs).
The difference percentages are even different when running headless and not headless, so I suppose this could be timing/animations related. I'd like to point out that we've been running wdio for visual regressions for some time now without much trouble.

I can't point to any specific cause for the time being, this is me just wondering, heads-up.

**Environment:**
 - Node.js version: 12.22.1
 - NPM version: 6.14.12
 - Browser name and version: Chrome 90
 - Platform name and version: macOS Big Sur
 - WebdriverIO version: 7.x (@wdio)
 - wdio-image-comparison-service version: 2.3.0

The project is an Ionic app, testing done on desktop.

**Comment by wswebcreation** [comment]
Hi @zarko-tg 

Thanks for the headsup, do you also have an example of the diffs?

From what I've seen in the past is that fonts are rendered differently between versions which causes most of the issues, is that also now the case?

**Comment by zarko-tg** [comment]
Don't have much yet cause I had to push the investigation a bit. It doesn't seem anything visually specific causing it. For example I am getting an actual with a popup in the midst of its animation. If I am to guess 10-20% of my tests are failing.
Let's see if others get the same problem now that stable Chrome 90 is out on desktop. I'll let you know what I find on my own asap, it might even turn out I've written some fragile tests :)

**Comment by wswebcreation** [comment]
Ok, thanks, will wait for it

**Comment by zarko-tg** [comment]
Never mind, even though these are unexpected failures due to Chrome update I decided to fix few pixels (new baseline images) and slow down here and there. Due to time constrains I didn't go much into the origin of the issue. Thanks anyway.
