### ISSUE TITLE
string template to distinguish whether it is a headless browser in formatImageName field?

### ISSUE THREAD

**Issue by itamud** [wswebcreation/wdio-image-comparison-service#67]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find me on Gitter](https://gitter.im/wswebcreation/protractor-image-comparison)
is there any string template or any way to distinguish whether it is a headless browser in formatImageName field?

**If it's about a specific piece of code, try and include some of it to support your question.**

for example:
```bash
formatImageName: "{tag}-{browserName}-{headlessBrowserName}-{browserVersion}-{width}x{height}-dpr-{dpr}",
```

**Environment (please complete the following information):**
 - Node.js version: [e.g. 8.9.1]
 - NPM version: [e.g. 5.8.0]
 - Browser name and version: [e.g. Chrome 68]
 - Platform name and version: [e.g. Windows 10]
 - WebdriverIO version: [e.g. 5.1.0]
 - wdio-image-comparison-service version: [e.g. 2.0.0]

**Additional context**

**Comment by wswebcreation** [comment]
Hi @itamud 

Can you provide some more info about what you want?

**Comment by itamud** [comment]
> Hi @itamud
> 
> Can you provide some more info about what you want?

What I want is a "string template" like `{browserMode}` in `formatImageName`, whose value is `headless` when running in headless browser and `normal` when running in normal browser.

The reason I want this kind of "string template" is to prevent comparing normal mode chrome with headless mode chrome.

Is something similar already exists? If not, is it possible to add this kind of string template?

Any help would be grateful
