### ISSUE TITLE
WDIO webdriver-image-comparison not working on node v.16.8.0

### ISSUE THREAD

**Issue by opensourcesensor** [wswebcreation/wdio-image-comparison-service#69]
- Node.js version: 16.8.0
 - NPM version: 7.21.0
 - Browser name and version: Chrome latest
 - Platform name and version: Windows 10
 - WebdriverIO version: latest
 - wdio-image-comparison-service version: latest

Hi all,
since I changed to node v.16.8.0, 
the wdio-image-comparison-service is not working.
"[chrome 92.0.4515.107 windows #0-0] TypeError: browser.checkScreen is not a function"

[wdio.conf.js.txt](https://github.com/wswebcreation/wdio-image-comparison-service/files/7097640/wdio.conf.js.txt)
[testcase.txt](https://github.com/wswebcreation/wdio-image-comparison-service/files/7097645/testcase.txt)
[ERROR_LOCAL_0209.txt](https://github.com/wswebcreation/wdio-image-comparison-service/files/7097676/ERROR_LOCAL_0209.txt)

Does anyone of you use this service with node version 16.8.0?

**Comment by wswebcreation** [comment]
@opensourcesensor 

This is the error

```
Error: The module '\\?\C:\Webdriver\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I need to see if I can fix this

**Comment by opensourcesensor** [comment]
Hi @wswebcreation ,
maybe interesting:
started on GitLab,
there is also an error with this canvas.node:

"Error: /builds/cd-it/ba-e/projects/web-experience/infrastructure/playground/wdio_tests/node_modules/canvas/build/Release/canvas.node: invalid ELF header"

[ERROR_GITLAB_16.8.0.txt](https://github.com/wswebcreation/wdio-image-comparison-service/files/7098312/ERROR_GITLAB_16.8.0.txt)

Does this have the same cause?

**Comment by wswebcreation** [comment]
Yes, that might be related. I think I need to update nodeCanvas.

**Comment by wswebcreation** [comment]
Hi @opensourcesensor 

I've updated all dependencies and use the latest version of Canvas. The GitHub Action that tests this project now also runs on NodeJS 16 and all WDIO test dependencies are updated to 7 and Async mode.

Locally and on GitHub Actions it passes, can you check with the latest version, which is https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v3.0.0

**Comment by Poitrin** [comment]
> The GitHub Action that tests this project now also runs on NodeJS 16 and all WDIO test dependencies are updated to 7 and Async mode.

Hi @wswebcreation ,
thank you so much for this fantastic plugin, which we use a lot in our projects!
I just wanted to mention that the 3.0.0 release note contains a typo:
all tests are written in _Sync_ mode → all tests are written in *async* mode

**Comment by wswebcreation** [comment]
Hi @Poitrin 

Thanks, changed it
