### ISSUE TITLE
saveScreen ->removeElements does not work in async mode

### ISSUE THREAD

**Issue by RossVertizan** [wswebcreation/wdio-image-comparison-service#70]
Firstly, I acknowledge that this may be a problem with the underlying webdriver-image-comparison module, but:
1. I don't know how to perform the same test using raw webdriver-image-comparison - the documentation is currently sparse.
2. The error relates to the change from WDIO [sync mode to async mode](https://github.com/webdriverio/webdriverio/discussions/6702)

**Environment (please complete the following information):**
 - Node.js version: v14.17.5
 - NPM version: 7.19.1
 - Browser name and version: Chrome 92.0.4515.159
 - Platform name and version: Windows 10 Version 21H1 (OS Build 19043.1165)
 - WebdriverIO version: 7.11.1
 - wdio-image-comparison-service version: 2.3.0

**Config of WebdriverIO + wdio-image-comparison-service**
Added wdio-image-comparison-service as a service in wdio.conf.js:
```json
services: [
        ['chromedriver'],
        ['image-comparison']
    ],
```

**Describe the bug**
When using saveScreen in wdio sync mode (@wdio/sync), the removeElements works.  When switching to async mode (either with @wdio/sync installed or removed) the removeElements does not work.  An example will be provided.

**To Reproduce**
See the example in the repository [here](https://github.com/RossVertizan/webdriverio_7289) and follow the instructions in the README_IMAGE_COMPARISON.md file.

**Expected behavior**
I expected that removeElements would work in async mode.

**Comment by wswebcreation** [comment]
Hi @RossVertizan 

Have you tried this

```js
        await browser.saveScreen('screenshot_async', {
            removeElements: [await LoginPage.pageFooter]
        })
```

The element first needs to be resolved before the module can use it

**Comment by RossVertizan** [comment]
Aghhh - no I haven't - of course!
 ... checking ...
Yes, that's it - sorry to have bothered you.
I hope this helps someone else.

**Comment by wswebcreation** [comment]
No problem!
