### ISSUE TITLE
Folder create/ image save on GitLab

### ISSUE THREAD

**Issue by opensourcesensor** [wswebcreation/wdio-image-comparison-service#73]
Hi all,
I am using the wdio-image-comparison-service in my project.
I have the project on gitlab and start the tests via Image.
The tests are deployed on a docker imag, (image: node:14.17.1-buster)
running on a gitlab pipeline.
FYI: The tests are connected to saucelabs.

On local, following folders are generated automatically:
![Local](https://user-images.githubusercontent.com/46485747/134301143-1f20afbb-00df-4735-943c-9432f0a49279.JPG)

- .tmp/actual/-> here are the actual images
- .tmp/fixx/-> here are the images with diffs

- wic/baseline/-> here are the baseline images 

By chance I noticed that these folders on gitlab are not changed / overwritten during a run on gitlbab. I then deleted them and started the run on gitlab - but no folders were generated:
![GitLab](https://user-images.githubusercontent.com/46485747/134301221-387a9595-35f6-46f5-851b-de1b6332876e.JPG)

Nevertheless it shows the individual pictures comparisons as successful - I wonder on what basis he compares the pictures?

I use the following config:
['image-comparison',
        {
            formatImageName: '{tag}-{logName}-{width}x{height}',
            savePerInstance: true,
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutToolBar: true,
            isHybridApp: true,
            tabbableOptions:{
                circle:{
                    size: 18,
                    fontSize: 18,
                },
                line:{
                    color: '#ff221a',
                    width: 3,
                },
            }
        }]

 - Node.js version: [14.17.6]
 - NPM version: [6.15.14]
 - Browser name and version: [Chrome latest]
 - Platform name and version: [Windows 10]
 - WebdriverIO version: [latest]
 - wdio-image-comparison-service version: [v 3.0]

Does someone of you use this service also on GitLab,
or know the issue?

Thanks for your help,
BR
Fabian Schmider

**Comment by wswebcreation** [comment]
Hi @opensourcesensor 

I'm not familiar with GitLab, but what happens, based on your config is the following:

when WDIO is started it will 
- save images in a separate folder by using this `savePerInstance: true`
- auto save a baseline image if no image is found by using this `autoSaveBaseline: true`

When you don't provide a baseline, or the module can't find the baseline, it will automatically create that baseline by simply copying the actual screenshot to the baseline folder. It will then use that baseline to compare against the actual image which will result in something like `expect(true).toEqual(true)` making your tests succeed.

You might need to check where the folders are created on GitLab to see what is really happening. You could enable the `debug: true,` in the config of the image-compare module to get extra logs printed with hopefully some paths

**Comment by opensourcesensor** [comment]
Hi @wswebcreation ,
thank you. 
Yes, that information is known for me, with the automatically creation of the path.
--> I start the tests with debug:true, and returnAllCompareData:true - the paths I use local are correct and the same paths are used on gitlab.
I think I found the reason:
I changed the baseline image with the same name, another image content.
**Local: 79% difference -> it created the diff image and the actual image
Gitlab: 79% difference -> it does not create a diff image or actual image**
Means the comparison is working, but I think they generate the data on the docker image - means the generated images(diff and actual) came not back to gitlab.

So as the functionality is given, the comparison works, I will upload all baseline images to gitlab, then this issue is solved. 
--> I can see the diff images in the console, so I can generate them local or have a look at the website, if there are differences.
Means this issue is solved!

Just another short question regarding this, maybe you know the answer:
For testing. I added the lines for fix the paths:
**baselineFolder: join(process.cwd(), '.test/sauceLabsBaseline/'),
screenshotPath: join(process.cwd(), '.tmp/'),**
--> Then the error occurs 
`Failed loading configuration file: C:\Webdriver\wdio.chrome.js: join is not defined`
`ReferenceError: join is not defined`
I did not find anything about this join is missing in the wdio/image comparison issue documentation.
I have installed the wdio-image-service on another PC, same error.

Do you have this issue once/know how to solve?

Many thanks,
BR
Fabian Schmider

**Comment by wswebcreation** [comment]
Sorry for missing this

> Failed loading configuration file: C:\Webdriver\wdio.chrome.js: join is not defined
> ReferenceError: join is not defined

This means that you didn't include `join` from the NodeJS module `path`, see also this code https://github.com/wswebcreation/wdio-image-comparison-service/blob/main/tests/configs/wdio.saucelabs.conf.js#L1

Going to close this issue now because it's solved, it's still open for questions
