### ISSUE TITLE
On the iOS 15 our DOM elements screenshots are shifted

### ISSUE THREAD

**Issue by Sam55555** [wswebcreation/wdio-image-comparison-service#76]
> **NOTE: Be aware of the fact that this module is only a plugin that provides all functionality from [`webdriver-image-comparison`](https://github.com/wswebcreation/webdriver-image-comparison). So please check if this is an issue with this plugin or with `webdriver-image-comparison`.**

**Environment (please complete the following information):**
 - Node.js version: [14.17.0]
 - NPM version: [6.14.13]
 - Browser name and version: [iOS 15 Safari]
 - Platform name and version: [iOS 15]
 - WebdriverIO version: [7.7.8]
 - wdio-image-comparison-service version: [3.1.0]

**Config of WebdriverIO + wdio-image-comparison-service**
Attached zip

**Describe the bug**
On the iOS 15 our DOM elements screenshots are shifted up by about size of the status bar
**To Reproduce**
[[iOS_15_Test_Project.zip](https://github.com/wswebcreation/wdio-image-comparison-service/files/7642359/iOS_15_Test_Project.zip)]

**Expected behavior**
iOS 15 has the same screenshots as previous versions (iOS 14) without shifting

**Comment by Sam55555** [comment]
Hi, is there any update?

**Comment by gaunap** [comment]
This issue blocks us massively. iOS 14 has bugs which prevents us using it. Since we cannot make the update to 15 our tests are deactivated. Any chance this issue get fixed in near time?

**Comment by wswebcreation** [comment]
Will be fixed in this PR https://github.com/wswebcreation/webdriver-image-comparison/pull/110

**Comment by wswebcreation** [comment]
A new version, `4.0.0` has been released and has a lot of improvements and fixes, can you please try again @Sam55555 and @gaunap
