### ISSUE TITLE
Return types of some functions are not set to promises, and cause ESLint to throw an error

### ISSUE THREAD

**Issue by c-trimm** [wswebcreation/wdio-image-comparison-service#77]
**Environment (please complete the following information):**
 - Node.js version: 16.10.0
 - NPM version: 7.24.0
 - Browser name and version: Chrome
 - Platform name and version: OSX
 - WebdriverIO version: ^7.11.0
 - wdio-image-comparison-service version: ^3.1.0

**Config of WebdriverIO + wdio-image-comparison-service**
tsconfig:
```
"types": [
    "node",
    "@wdio/cucumber-framework",
    "@wdio/devtools-service",
    "expect-webdriverio",
    "webdriverio/async"
],
```

**Describe the bug**
The return types on some of the functions supplied by `types/index.d.ts` appear to be incorrect. The one I am currently encountering is for `checkFullPageScreen`. When writing `await browser.checkFullPageScreen('...')`, I receive the message
```
ESLint: Unexpected `await` of a non-Promise (non-"Thenable") value.(@typescript-eslint/await-thenable)
```
In the `index.d.ts` file, it has the return type as `Result` without a promise, while the actual function in `webdriver-image-comparison` has the return type of `Promise<ImageCompareResult | number>`.

**To Reproduce**

Something like this will show the error if you have ESLint installed:
```
expect(await browser.checkFullPageScreen('viewer_textbox_default_text')).toEqual(0)
```

**Expected behavior**
It should not show the error because if the return type supports promises, it will allow it to be awaited.

**Log**
n/a

**Additional context**
n/a

**Comment by wswebcreation** [comment]
Closing this one because it will be fixed with https://github.com/wswebcreation/wdio-image-comparison-service/pull/93
