### ISSUE TITLE
WinAppDriver Supported?

### ISSUE THREAD

**Issue by flymike** [wswebcreation/wdio-image-comparison-service#78]
**Describe your question with as much detail as possible**
Tried this service with wdio/winappdriver/jasmine/typescript, setup seems OK but the actual check*/save* methods on the selected element have the same "not a function" error.

Possible to make this service working with winappdriver for Windows Desktop App testing?

**Comment by wswebcreation** [comment]
Thanks for asking @flymike 

But this module only works for web apps, AFAIK all apps for Windows Desktop are "more native". You might want to check https://github.com/wswebcreation/wdio-native-app-compare/
