### ISSUE TITLE
A consolidated report in html for all difference found with actual and diff image

### ISSUE THREAD

**Issue by psubrambe** [wswebcreation/wdio-image-comparison-service#8]
**Is your feature request related to a problem? Please describe.**
Now all the diff needs to be located in Diff folder is there is anyway we make this html report.

**Describe the solution you'd like**
A consolidated report for actual and diff in html format

**Comment by wswebcreation** [comment]
Hi @psubrambe 

Thanks for the feature request,  but this will never be part of this module. If it will be created it will be a separate module.

You can also build it on your own based on the provided data from the responses. Going to close it for now
